In [1]:
import numpy as np

## Задача

Сгенерировать вектор из 100 элементов и превратить его в:

- матрицу 10x10
- вектор 1x100
- вектор 100x1

In [3]:
vector = np.arange(100)

matrix10 = vector.reshape(10, 10)
vec1 = vector.reshape(1, 100)
vec2 = vector.reshape(100, 1)

print(matrix10.shape, vec1.shape, vec2.shape)

(10, 10) (1, 100) (100, 1)


## Задача - Решение СЛАУ

$Ax = b$

Функция обратной матрицы - `np.linalg.inv(A)`

Решение СЛАУ выглядит так:

$Ax = b$

$A^{-1}Ax=A^{-1}b$

$x=A^{-1}b$

In [5]:
A = np.array([
    [3, -2],
    [5, 1]]
)
b = np.array([-6, 3])
# Решение - [0, 3]
x = np.linalg.inv(A) @ b
x

array([1.11022302e-16, 3.00000000e+00])

In [6]:
np.linalg.solve(A, b)

array([0., 3.])

## Задача

Сгенерировать случайную матрицу и посчитать сумму положительных элементов в каждой строке, в каждом столбце.

In [12]:
a = np.random.uniform(-1, 1, size=(5, 3))
a[a < 0] = 0

In [13]:
a.sum(axis=0)

array([1.45412721, 0.69746327, 0.79263092])

In [14]:
a.sum(axis=1)

array([0.4265673 , 0.4297739 , 0.77118111, 0.79730625, 0.51939283])

## Задача

Вывести матрицу из нулей и единиц в шахматном порядке

In [18]:
n = 5
m = np.zeros((n, n))

m[::2, ::2] = 1
m[1::2, 1::2] = 1

m

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

## Задача

Решим СЛАУ 2 порядка методом Крамера

https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0

На практике этот метод неэффективен, но зато позволяет разобраться с индексацией

In [21]:
A = np.array([
    [3, -2],
    [5, 1]]
)
b = np.array([-6, 3])

A1 = A.copy()
A2 = A.copy()

A1[:, 0] = b
A2[:, 1] = b

delta = np.linalg.det(A)
delta1 = np.linalg.det(A1)
delta2 = np.linalg.det(A2)

if delta == 0:
    x = None
    print('Корней нет')
else:
    x = [delta1 / delta, delta2 / delta]
    print(x)

[0.0, 2.9999999999999996]


Решение можно оформить в функцию

In [22]:
def solve_cramer(A, b):
    A1 = A.copy()
    A2 = A.copy()
    A1[:, 0] = b
    A2[:, 1] = b

    delta = np.linalg.det(A)
    delta1 = np.linalg.det(A1)
    delta2 = np.linalg.det(A2)

    if delta == 0:
        return None
    else:
        return [delta1 / delta, delta2 / delta]

Сравним скорость решения метода Крамера и стандартного способа, реализованного в numpy

In [26]:
%%timeit
solve_cramer(A, b)

20.3 µs ± 967 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
%%timeit
np.linalg.solve(A, b)

6.72 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


numpy решает в 3 раза быстрее даже для матрицы 2х2